### File Vagrantfile

# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"
  config.ssh.insert_key = false

  NodeCount = 2

  (1..NodeCount).each do |i|

    config.vm.define "ubuntuvm#{i}" do |node|
      node.vm.box               = "generic/ubuntu2004"
      node.vm.box_check_update  = false
      node.vm.box_version       = "3.3.0"
      node.vm.hostname          = "ubuntuvm#{i}.example.com"

      node.vm.network "private_network", ip: "172.16.16.10#{i}"
      node.vm.network "public_network", :dev => "vlan2341", :mode => 'bridge', :type => "bridge"

      ## Bo cac dong comment sau de dat IP tinh
      ###
      #node.vm.network "public_network", :dev => "vlan2341", :mode => 'bridge', :type => "bridge", :ip => "172.16.70.189"
      #node.vm.provision "shell",
      #run: "always",
      #inline: "route add default gw 172.16.70.1"
      ###

      # delete default gw on eth0
      node.vm.provision "shell",
      run: "always",
      inline: "ip route del default via 192.168.121.1 || true"

      node.vm.provider :virtualbox do |v|
        v.name    = "ubuntuvm#{i}"
        v.memory  = 1024
        v.cpus    = 1
      end

      node.vm.provider :libvirt do |v|
        v.nested  = true
        v.memory  = 1024
        v.cpus    = 1
      end
    end
  end
end