# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
BOX_IMAGE_CENTOS7 = "centos/7"
BOX_IMAGE_UBUNTU20= "generic/ubuntu2004"

Vagrant.configure(2) do |config|

  #config.vm.provision "shell", path: "bootstrap.sh"

  # VM MGNT
  config.vm.define "mgmt01" do |mgmt01|
    mgmt01.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 2
      v.storage :file, :size => '20G' #them o cung thu 2
      # v.graphics_ip = '0.0.0.0'
			# vm.storage_pool_name = 'kvm2' # Cau hinh noi luu VM. Su dung lenh "pool-list virsh"  de lay ten cua pool.
    end 
    mgmt01.vm.box = BOX_IMAGE_CENTOS7
    mgmt01.vm.box_check_update  = false
    mgmt01.vm.hostname = "mgmt01"
		mgmt01.vm.network :private_network, ip: "10.0.0.2"
    mgmt01.vm.provision "shell", path: "boostrap_centos7.sh"
  end

  # VM NODE01 
  config.vm.define "node01" do |node01|
    node01.vm.provider "libvirt" do |v|
      v.memory = 1024
      v.cpus = 1
      v.storage :file, :size => '20G' #them o cung thu 2
			# vm.storage_pool_name = 'kvm2' # Cau hinh noi luu VM. Su dung lenh "pool-list virsh"  de lay ten cua pool.			
      # v.graphics_ip = '0.0.0.0'
    end
    node01.vm.box = BOX_IMAGE_UBUNTU20
    node01.vm.box_check_update  = false
    node01.vm.hostname = "node01"
    node01.vm.network :private_network, ip: "10.0.0.3"
    node01.vm.provision "shell", path: "bootstrap_ubuntu20.sh"
  end

  # VM NODE02
  config.vm.define "node02" do |node02|
    node02.vm.provider "libvirt" do |v|
      v.memory = 1024
      v.cpus = 1
      v.storage :file, :size => '20G' #them o cung thu 2
			# vm.storage_pool_name = 'kvm2' # Cau hinh noi luu VM. Su dung lenh "pool-list virsh"  de lay ten cua pool.
      # v.graphics_ip = '0.0.0.0'
    end
    node02.vm.box = BOX_IMAGE_UBUNTU20
    node02.vm.box_check_update  = false
    node02.vm.hostname = "node02"
    node02.vm.network :private_network, ip: "10.0.0.4"
    node02.vm.provision "shell", path: "bootstrap_ubuntu20.sh"
  end

  # VM NODE03
  config.vm.define "node03" do |node03|
    node03.vm.provider "libvirt" do |v|
      v.memory = 1024
      v.cpus = 1
      v.storage :file, :size => '20G' #them o cung thu 2
			# vm.storage_pool_name = 'kvm2' # Cau hinh noi luu VM. Su dung lenh "pool-list virsh"  de lay ten cua pool.
      # v.graphics_ip = '0.0.0.0'
    end
    node03.vm.box = BOX_IMAGE_CENTOS7
    node03.vm.box_check_update  = false
    node03.vm.hostname = "node03"
    node03.vm.network :private_network, ip: "10.0.0.5"
    node03.vm.provision "shell", path: "boostrap_centos7.sh"
  end

end