# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
BOX_IMAGE_MNGT = "centos/7"
BOX_IMAGE_NODE= "generic/ubuntu2004"

Vagrant.configure(2) do |config|

  #config.vm.provision "shell", path: "bootstrap.sh"

  # VM MGNT
  config.vm.define "mgmt01" do |mgmt|
    mgmt.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 2
    end 
    mgmt.vm.box = BOX_IMAGE
    mgmt.vm.network :private_network, ip: "10.0.0.2"
		mgmt.vm.provision "shell", path: "boostrap_centos7.sh"
  end

  # VM NODE1 
  config.vm.define "node1" do |node1|
    node1.vm.provider "libvirt" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    node1.vm.box = BOX_IMAGE_NODE
    node1.vm.network :private_network, ip: "10.0.0.5"
		node1.vm.provision "shell", path: "bootstrap_ubuntu20.sh"
  end

end