# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
BOX_IMAGE_MNGT = "centos/7"
BOX_IMAGE_NODE= "generic/ubuntu2004"

Vagrant.configure(2) do |config|

  #config.vm.provision "shell", path: "bootstrap.sh"

  # VM MGNT
  config.vm.define "mgmt0101" do |mgmt01|
    mgmt01.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 2
    end 
    mgmt01.vm.box = BOX_IMAGE_MNGT
    mgmt01.vm.box_check_update  = false
    mgmt01.vm.hostname = "mgmt01"
    mgmt01.vm.network :private_network, ip: "10.0.0.2"
    mgmt01.vm.provision "shell", path: "boostrap_centos7.sh"
  end

  # VM NODE01 
  config.vm.define "node01" do |node01|
    node01.vm.provider "libvirt" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    node01.vm.box = BOX_IMAGE_NODE
    node01.vm.box_check_update  = false
    node01.vm.hostname = "node01"
    node01.vm.network :private_network, ip: "10.0.0.5"
    node01.vm.provision "shell", path: "bootstrap_ubuntu20.sh"
  end

end