# -*- mode: ruby -*-
# vi: set ft=ruby :
# wget http://download.cirros-cloud.net/0.5.2/cirros-0.5.2-x86_64-disk.img
ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

BOX_IMAGE= "generic/ubuntu2004"
PATH_SHELL = "bootstrap_ubuntu20.sh"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE

  config.vm.provision "shell", path: PATH_SHELL

  config.ssh.insert_key = false
	
  # VM CTL01 
  config.vm.define "ctl01" do |ctl01|
    ctl01.vm.box = BOX_IMAGE
    ctl01.vm.box_check_update  = false
    ctl01.vm.hostname = "ctl01"
    ctl01.vm.network "private_network", ip: "172.16.16.90"
    ctl01.vm.network "public_network", dev: "vlan2341", mode: "bridge", type: "bridge", ip: "172.16.70.171"
    # ctl01.vm.network "public_network", dev: "vlan2342", mode: "bridge", type: "bridge", ip: "172.16.71.171"
    ctl01.vm.network "public_network", dev: "vlan2342", mode: "bridge", type: "bridge" #VLAN Provider
    ctl01.vm.network "public_network", dev: "vlan2344",mode: "bridge", type: "bridge", ip: "172.16.73.171" # VLAN CEPH-COM
    ctl01.vm.provider "libvirt" do |v|
      v.memory = 6144
      v.cpus = 2		
      v.storage_pool_name = 'kvm2' # Cau hinh noi luu VM. Su dung lenh "virsh pool-list"  de lay ten cua pool.
      v.storage :file, :size => '60G' #them o cung thu 2			
      v.storage :file, :size => '60G' #them o cung thu 3			
      v.storage :file, :size => '60G' #them o cung thu 4			
      # v.graphics_ip = '0.0.0.0'
    end
  end
  
  # VM COM01 
  config.vm.define "com01" do |com01|
    com01.vm.box = BOX_IMAGE
    com01.vm.box_check_update  = false
    com01.vm.hostname = "com01"
    com01.vm.network "private_network", ip: "172.16.16.91"
    com01.vm.network "public_network", dev: "vlan2341", mode: "bridge", type: "bridge", ip: "172.16.70.175"
    #com01.vm.network "public_network", dev: "vlan2342", mode: "bridge", type: "bridge", ip: "172.16.71.175"
    com01.vm.network "public_network", dev: "vlan2342", mode: "bridge", type: "bridge"  #VLAN Provider
    com01.vm.network "public_network", dev: "vlan2344",mode: "bridge", type: "bridge", ip: "172.16.73.175" # VLAN CEPH-COM
    com01.vm.provider "libvirt" do |v|
      # v.memory = 8192
      v.memory = 12288
      v.cpus = 4			
      v.storage_pool_name = 'kvm2' # Cau hinh noi luu VM. Su dung lenh "virsh pool-list"  de lay ten cua pool.
      v.storage :file, :size => '60G' #them o cung thu 2					
      # v.graphics_ip = '0.0.0.0'
    end	  
  end

  # VM COM02 
  config.vm.define "com02" do |com02|
    com02.vm.box = BOX_IMAGE
    com02.vm.box_check_update  = false
    com02.vm.hostname = "com02"
    com02.vm.network "private_network", ip: "172.16.16.92"
    com02.vm.network "public_network", dev: "vlan2341", mode: "bridge", type: "bridge", ip: "172.16.70.176"
    #com02.vm.network "public_network", dev: "vlan2342", mode: "bridge", type: "bridge", ip: "172.16.71.176"
    com02.vm.network "public_network", dev: "vlan2342", mode: "bridge", type: "bridge" #VLAN Provider
    com02.vm.network "public_network", dev: "vlan2344",mode: "bridge", type: "bridge", ip: "172.16.73.176" # VLAN CEPH-COM
    com02.vm.provider "libvirt" do |v|
      # v.memory = 8192
      v.memory = 12288
      v.cpus = 4			
      v.storage_pool_name = 'kvm2' # Cau hinh noi luu VM. Su dung lenh "virsh pool-list"  de lay ten cua pool.
      v.storage :file, :size => '60G' #them o cung thu 2			
      # v.graphics_ip = '0.0.0.0'
    end	  
  end
  
  # VM NFS 
  config.vm.define "nfs01" do |nfs01|
    nfs01.vm.box = BOX_IMAGE
    nfs01.vm.box_check_update  = false
    nfs01.vm.hostname = "nfs01"
    nfs01.vm.network "private_network", ip: "172.16.16.96"
    nfs01.vm.network "public_network", dev: "vlan2341", mode: "bridge", type: "bridge", ip: "172.16.70.179"
    # nfs01.vm.network "public_network", dev: "vlan2342", mode: "bridge", type: "bridge", ip: "172.16.71.179"
    nfs01.vm.network "public_network", dev: "vlan2344",mode: "bridge", type: "bridge", ip: "172.16.73.179" # VLAN CEPH-COM
    nfs01.vm.provider "libvirt" do |v|
      v.memory = 4096
      v.cpus = 4			
      v.storage_pool_name = 'kvm2' # Cau hinh noi luu VM. Su dung lenh "virsh pool-list"  de lay ten cua pool.
      v.storage :file, :size => '100G' #them o cung thu 2			
      v.storage :file, :size => '120G' #them o cung thu 3			
      # v.graphics_ip = '0.0.0.0'
    end	  
  end  
end