# -*- mode: ruby -*-
# vi: set ft=ruby :
# wget http://download.cirros-cloud.net/0.5.2/cirros-0.5.2-x86_64-disk.img
ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

BOX_IMAGE= "generic/ubuntu2004"
PATH_SHELL = "bootstrap_ubuntu20.sh"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE

  config.vm.provision "shell", path: PATH_SHELL

  config.ssh.insert_key = false
	
  # VM ceph01 
  config.vm.define "ceph01" do |ceph01|
    ceph01.vm.box = BOX_IMAGE
    ceph01.vm.box_check_update  = false
    ceph01.vm.hostname = "ceph01"
    ceph01.vm.network "private_network", ip: "172.16.16.95"
    ceph01.vm.network "public_network", :dev => "vlan2341", :mode => 'bridge', :type => "bridge", :ip => "172.16.70.95"
    ceph01.vm.provider "libvirt" do |v|
      v.memory = 8192
      v.cpus = 4			
      v.storage_pool_name = 'kvm2' # Cau hinh noi luu VM. Su dung lenh "virsh pool-list"  de lay ten cua pool.
      v.storage :file, :size => '60G' #them o cung thu 2			
      v.storage :file, :size => '60G' #them o cung thu 2			
      v.storage :file, :size => '60G' #them o cung thu 2			
      # v.graphics_ip = '0.0.0.0'
    end
  end
  
  # VM ceph02 
  config.vm.define "ceph02" do |ceph02|
    ceph02.vm.box = BOX_IMAGE
    ceph02.vm.box_check_update  = false
    ceph02.vm.hostname = "ceph02"
    ceph02.vm.network "private_network", ip: "172.16.16.96"
    ceph02.vm.network "public_network", :dev => "vlan2341", :mode => 'bridge', :type => "bridge", :ip => "172.16.70.96"
    ceph02.vm.provider "libvirt" do |v|
      v.memory = 8192
      v.cpus = 4			
      v.storage_pool_name = 'kvm2' # Cau hinh noi luu VM. Su dung lenh "virsh pool-list"  de lay ten cua pool.
      v.storage :file, :size => '60G' #them o cung thu 2			
      v.storage :file, :size => '60G' #them o cung thu 2			
      v.storage :file, :size => '60G' #them o cung thu 2			
      # v.graphics_ip = '0.0.0.0'
    end	  
  end

  # VM ceph03 
  config.vm.define "ceph03" do |ceph03|
    ceph03.vm.box = BOX_IMAGE
    ceph03.vm.box_check_update  = false
    ceph03.vm.hostname = "ceph03"
    ceph03.vm.network "private_network", ip: "172.16.16.97"
    ceph03.vm.network "public_network", :dev => "vlan2341", :mode => 'bridge', :type => "bridge", :ip => "172.16.70.97"
    ceph03.vm.provider "libvirt" do |v|
      v.memory = 4096
      v.cpus = 2			
      v.storage_pool_name = 'kvm2' # Cau hinh noi luu VM. Su dung lenh "virsh pool-list"  de lay ten cua pool.
      v.storage :file, :size => '60G' #them o cung thu 2			
      v.storage :file, :size => '60G' #them o cung thu 2			
      v.storage :file, :size => '60G' #them o cung thu 2			
      # v.graphics_ip = '0.0.0.0'
    end	  
  end

  # VM client01 
  config.vm.define "client01" do |client01|
    client01.vm.box = BOX_IMAGE
    client01.vm.box_check_update  = false
    client01.vm.hostname = "client01"
    client01.vm.network "private_network", ip: "172.16.16.98"
    client01.vm.network "public_network", :dev => "vlan2341", :mode => 'bridge', :type => "bridge", :ip => "172.16.70.98"
    client01.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 2			
      v.storage_pool_name = 'kvm2' # Cau hinh noi luu VM. Su dung lenh "virsh pool-list"  de lay ten cua pool.
      # v.storage :file, :size => '60G' #them o cung thu 2			
      # v.storage :file, :size => '60G' #them o cung thu 2			
      # v.storage :file, :size => '60G' #them o cung thu 2			
      # v.graphics_ip = '0.0.0.0'
    end	  
  end

end