# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

BOX_IMAGE= "generic/ubuntu1804"
PATH_SHELL = "bootstrap.sh"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE

  config.vm.provision "shell", path: PATH_SHELL
  config.vm.provision "file", source: "local-sample.conf", destination: "/tmp/local.conf"
  config.vm.provision "file", source: "cirros-0.5.2-x86_64-disk.img", destination: "/tmp/cirros-0.5.2-x86_64-disk.img"
  config.ssh.insert_key = false
	
  # VM Devstack 
  config.vm.define "devstack01" do |devstack01|
    devstack01.vm.box = BOX_IMAGE
    devstack01.vm.box_check_update  = false
    devstack01.vm.hostname = "devstack01"

    devstack01.vm.network "private_network", ip: "172.16.16.101"
    devstack01.vm.network "public_network", :dev => "vlan2341", :mode => 'bridge', :type => "bridge", :ip => "172.16.70.189"
    devstack01.vm.provider "libvirt" do |v|
      v.memory = 8192
      v.cpus = 4			
      v.storage_pool_name = 'kvm2' # Cau hinh noi luu VM. Su dung lenh "virsh pool-list"  de lay ten cua pool.
      v.storage :file, :size => '90G' #them o cung thu 2			
      # v.graphics_ip = '0.0.0.0'
    end
    devstack01.vm.provision "shell", path: "devstack.sh"
  end
	  
end