# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

# Bo 2 dong duoi neu su dung he dieu hanh khac va mo comment 02 dong tiep theo.
# BOX_IMAGE = "centos/7"
# PATH_SHELL = "boostrap_centos7.sh"

# Mo comment 2 dong duoi de su dung he dieu hanh la Ubuntu 20.04 va comment 02 dong truoc do.
BOX_IMAGE= "generic/ubuntu1804"
PATH_SHELL = "bootstrap.sh"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE

  config.vm.provision "shell", path: PATH_SHELL
  config.ssh.insert_key = false

  # config.vm.synced_folder ".", "/vagrant", disabled: true
	config.vm.provision "file", source: "local-sample.conf", destination: "/tmp/local.conf"

  # VM Devstack 
  config.vm.define "devstack01" do |devstack01|
    devstack01.vm.box = BOX_IMAGE
    devstack01.vm.box_check_update  = false
    devstack01.vm.hostname = "devstack01"

    devstack01.vm.network "private_network", ip: "172.16.16.101"
    devstack01.vm.network "public_network", :dev => "vlan2341", :mode => 'bridge', :type => "bridge", :ip => "172.16.70.189"
		
    devstack01.vm.provision "shell", path: "install-devstack.sh"
		devstack01.vm.provider "libvirt" do |v|
      v.memory = 8192
      v.cpus = 4
			
      v.storage_pool_name = 'kvm2' # Cau hinh noi luu VM. Su dung lenh "virsh pool-list"  de lay ten cua pool.
      v.storage :file, :size => '90G' #them o cung thu 2			
      # v.graphics_ip = '0.0.0.0'
    end
  end

end