# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
BOX_IMAGE_CENTOS7 = "centos/7"
BOX_IMAGE_UBUNTU20= "generic/ubuntu2004"

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap_ubuntu20.sh"
  config.ssh.insert_key = false

  # VM master 
  config.vm.define "node01" do |node01|
    node01.vm.provider "libvirt" do |v|
      v.memory = 4096
      v.cpus = 4
      v.storage_pool_name = 'kvm2' # Cau hinh noi luu VM. Su dung lenh "virsh pool-list"  de lay ten cua pool.			
      # v.graphics_ip = '0.0.0.0'
    end
    node01.vm.box = BOX_IMAGE_UBUNTU20
    node01.vm.box_check_update  = false
    node01.vm.hostname = "node01"
    node01.vm.network :private_network, ip: "172.16.16.81"
    node01.vm.network "public_network", dev: "vlan2341", mode: "bridge", type: "bridge", ip: "172.16.70.81"
  end

  # VM node02
  config.vm.define "node02" do |node02|
    node02.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 2
      v.storage :file, :size => '20G' #them o cung thu 2
      v.storage_pool_name = 'kvm2' # Cau hinh noi luu VM. Su dung lenh "virsh pool-list"  de lay ten cua pool.
      # v.graphics_ip = '0.0.0.0'
    end
    node02.vm.box = BOX_IMAGE_UBUNTU20
    node02.vm.box_check_update  = false
    node02.vm.hostname = "node02"
    node02.vm.network :private_network, ip: "172.16.16.82"
    node02.vm.network "public_network", dev: "vlan2341", mode: "bridge", type: "bridge", ip: "172.16.70.82"
  end


end