# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
BOX_IMAGE_CENTOS7 = "centos/7"
BOX_IMAGE_UBUNTU20= "generic/ubuntu2004"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE_CENTOS7

  config.vm.provision "shell", path: "bootstrap.sh"
  config.ssh.insert_key = false

  # config.vm.synced_folder ".", "/vagrant", disabled: true

  # VM app01 
  config.vm.define "app01" do |app01|
    app01.vm.provider "libvirt" do |v|
      v.memory = 1024
      v.cpus = 1
      # v.storage_pool_name = 'kvm2' # Cau hinh noi luu VM. Su dung lenh "virsh pool-list"  de lay ten cua pool.			
      # v.graphics_ip = '0.0.0.0'
    end
    app01.vm.box = BOX_IMAGE_CENTOS7
    app01.vm.box_check_update  = false
    app01.vm.hostname = "app01"
    app01.vm.network :private_network, ip: "10.0.0.4"
    app01.vm.provision "shell", path: "bootstrap.sh"
  end

  # VM app02 
  config.vm.define "app02" do |app02|
    app02.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 2
      v.storage_pool_name = 'kvm2' # Cau hinh noi luu VM. Su dung lenh "virsh pool-list"  de lay ten cua pool.			
      # v.graphics_ip = '0.0.0.0'
    end
    app02.vm.box = BOX_IMAGE_CENTOS7
    app02.vm.box_check_update  = false
    app02.vm.hostname = "app02"
    app02.vm.network :private_network, ip: "10.0.0.5"
    app02.vm.provision "shell", path: "bootstrap.sh"
  end

  # VM db01 
  config.vm.define "db01" do |db01|
    db01.vm.provider "libvirt" do |v|
      v.memory = 4096
      v.cpus = 4
      v.storage_pool_name = 'kvm2' # Cau hinh noi luu VM. Su dung lenh "virsh pool-list"  de lay ten cua pool.			
      # v.graphics_ip = '0.0.0.0'
    end
    db01.vm.box = BOX_IMAGE_CENTOS7
    db01.vm.box_check_update  = false
    db01.vm.hostname = "db01"
    db01.vm.network :private_network, ip: "10.0.0.6"
    db01.vm.provision "shell", path: "bootstrap.sh"
  end
end